version: 2.1

jobs:
  build-deploy: # build for the master branch
    machine: true
    working_directory: ~/klaatu
    steps:
      - checkout
      - run:
          name: Build docker image and push to repo
          command: |
            docker version
            docker build -t klaatu .
            docker tag klaatu mozilla/klaatu:latest
            docker login -u "${DOCKERHUB_USER}" -p "${DOCKERHUB_PASS}"
            docker push mozilla/klaatu:latest
  build-release: # build for tags
    machine: true
    working_directory: ~/redash-ui-tests
    steps:
      - checkout
      - run:
          name: Build docker image and push to repo
          command: |
            docker version
            docker build -t klaatu .
            docker tag klaatu "mozilla/klaatu:${CIRCLE_TAG}"
            docker login -u "${DOCKERHUB_USER}" -p "${DOCKERHUB_PASS}"
            docker push "mozilla/klaatu:${CIRCLE_TAG}"
  lint:
    docker:
      - image: circleci/python:3.7-browsers
    steps:
      - checkout
      - restore_cache:
          key: klaatu-lint-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install tox
          command: sudo pip install tox
      - run:
          name: Lint files
          command: tox -e formatting
      - run:
          name: Run type check
          command: tox -e mypy
      - save_cache:
          key: klaatu-lint-{{ checksum "Pipfile.lock" }}
          paths:
            - .tox
  test-current-nightly:
    working_directory: ~/klaatu
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: klaatu-test-{{ checksum "Pipfile.lock" }}
      - run: 
          name: Build docker image
          command: docker build -t klaatu:latest .
      - run: 
          name: Run tests
          command: |
            set -ex
            docker run --name "klaatu" klaatu:latest tox -e exp-tests -- --experiment=fixtures/normandy-nextgen-study-example-a@mozilla.org-0.3-signed.xpi --html=test_results/report.html --private-browsing-enabled
            docker cp klaatu:/code/test_results/report.html ./report.html
      - save_cache:
          key: klaatu-test-{{ checksum "Pipfile.lock" }}
          paths:
            - .tox
      - store_artifacts:
          path: report.html
  test-old-nightly:
    working_directory: ~/klaatu
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: klaatu-test-{{ checksum "Pipfile.lock" }}
      - run: 
          name: Build docker image
          command: docker build -t klaatu:latest .
      - run: 
          name: Run tests
          command: |
            set -ex
            docker run --name "klaatu" klaatu:latest tox -e exp-tests -- --experiment=fixtures/normandy-nextgen-study-example-a@mozilla.org-0.3-signed.xpi --html=test_results/report.html --run-update-test --private-browsing-enabled
            docker cp klaatu:/code/test_results/report.html ./report.html
      - save_cache:
          key: klaatu-test-{{ checksum "Pipfile.lock" }}
          paths:
            - .tox
      - store_artifacts:
          path: report.html
  test-release-firefox:
    working_directory: ~/klaatu
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: klaatu-test-{{ checksum "Pipfile.lock" }}
      - run: 
          name: Build docker image
          command: docker build -t klaatu:latest .
      - run: 
          name: Run tests
          command: |
            set -ex
            docker run --name "klaatu" klaatu:latest tox -e exp-tests -- --experiment=fixtures/normandy-nextgen-study-example-a@mozilla.org-0.3-signed.xpi --html=test_results/report.html --run-firefox-release --private-browsing-enabled
            docker cp klaatu:/code/test_results/report.html ./report.html
      - save_cache:
          key: klaatu-test-{{ checksum "Pipfile.lock" }}
          paths:
            - .tox
      - store_artifacts:
          path: report.html
workflows:
  version: 2.1
  test_and_lint:
    jobs:
      - build-deploy:
           requires:
              - test-current-nightly
              - test-old-nightly
           filters:
             branches:
               only: master
      - build-release:
           requires:
              - test-current-nightly
              - test-old-nightly
           filters:
             tags:
               only: /.*/
             branches:
               ignore: /.*/
      - lint
      - test-current-nightly
      - test-old-nightly