version: 2.1

jobs:
  lint:
    docker:
      - image: circleci/python:3.7-browsers
    steps:
      - checkout
      - restore_cache:
          key: klaatu-lint-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install tox
          command: sudo pip install tox
      - run:
          name: Lint files
          command: tox -e formatting
      - save_cache:
          key: klaatu-lint-{{ checksum "Pipfile.lock" }}
          paths:
            - .tox
  test:
    docker:
      - image: circleci/python:3.7-browsers
    steps:
      - checkout
      - restore_cache:
          key: klaatu-test-{{ checksum "Pipfile.lock" }}
      - run: 
          name: Install tox
          command: sudo pip install tox
      - run:
          name: Run tests
          command: tox -e py37-exp-tests -- --experiment=fixtures/shield_study_example-2.0.0.zip
      - save_cache:
          key: klaatu-test-{{ checksum "Pipfile.lock" }}
          paths:
            - .tox
      - store_artifacts:
          path: results/exp-tests.html
workflows:
  version: 2.1
  test_and_lint:
    jobs:
      - lint
      - test